// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWi8YDSFlSuf21Bp8tGu6UdPk1WeLffuA',
    appId: '1:246340274449:web:ca86d7fd6a7f93c71324b0',
    messagingSenderId: '246340274449',
    projectId: 'real-estate-aad8f',
    authDomain: 'real-estate-aad8f.firebaseapp.com',
    storageBucket: 'real-estate-aad8f.appspot.com',
    measurementId: 'G-G14M9WYE22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbEgMHwUkfLBeXBMRiaZzWggG0nfjbr18',
    appId: '1:246340274449:android:84adc41653cb729d1324b0',
    messagingSenderId: '246340274449',
    projectId: 'real-estate-aad8f',
    storageBucket: 'real-estate-aad8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJc1Vqdj0Fj4HpGHv3DwwLVahng1dDu8k',
    appId: '1:246340274449:ios:025957e024d360791324b0',
    messagingSenderId: '246340274449',
    projectId: 'real-estate-aad8f',
    storageBucket: 'real-estate-aad8f.appspot.com',
    iosClientId: '246340274449-2p16nctk48mdpfd51jiu55lgj89s2udu.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate',
  );
}
